name: billing-fe
services:
  billing-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: billing-frontend:latest
    container_name: billing_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - billing-network

networks:
  billing-network:
    external: true
    name: billing-network
