ALTER TABLE `groups`
    MODIFY COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE subscriptions
    MODIFY COLUMN subscriber_type VARCHAR(30) NOT NULL,
    MODIFY COLUMN status VARCHAR(30) NOT NULL DEFAULT 'PENDING';

ALTER TABLE group_members
    MODIFY COLUMN role VARCHAR(30) NOT NULL DEFAULT 'MEMBER';

ALTER TABLE payment_records
    MODIFY COLUMN payment_status VARCHAR(30) NOT NULL;

ALTER TABLE certificate_provisioning_records
    MODIFY COLUMN status VARCHAR(30) NOT NULL DEFAULT 'PENDING';

ALTER TABLE user_accounts
    MODIFY COLUMN auth_provider VARCHAR(30) NOT NULL DEFAULT 'LOCAL',
    MODIFY COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE refresh_tokens
    MODIFY COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';
